import { Candidate, Assessment, Team, TeamInvite } from './types';

export const INITIAL_CANDIDATE: Candidate = {
  id: 'cand-alex-morgan',
  username: 'alexmorgan',
  name: 'Alex Morgan',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'Full Stack Developer',
  university: 'Tech University',
  bio: 'I build useful products with React, Python and AI.',
  location: 'San Francisco, CA (Remote OK)',
  githubUrl: 'https://github.com/alexmorgan',
  portfolioUrl: 'https://alexmorgan.dev',
  email: 'alex.morgan@techuniv.edu',
  overallConfidence: 87,
  verifiedSkillsCount: 3,
  lookingForTeam: true,
  hackathon: 'HackGenesis 2026',
  passportId: 'SF-PASS-8842-X7',
  issuedAt: 'March 2026',
  signature: '0x8f23...a94c (ECDSA Verified)',
  skills: [
    {
      id: 'skill-react',
      name: 'React',
      slug: 'react',
      category: 'frontend',
      status: 'VERIFIED',
      verificationLevel: 5,
      trustScore: 98,
      confidenceScore: 96,
      evidenceConfidence: 96,
      projectsFound: 5,
      repositoriesFound: 4,
      assessmentScore: 92,
      skillMaturity: 'Mastery',
      yearsOfExposure: 4.5,
      lastActiveDate: 'Sep 2026',
      verifiedAt: '2026-03-09',
      verificationHash: '0x7c49...32e1',
      level: 'Advanced',
      evidenceCounts: { projects: 5, repos: 4, certifications: 1 },
      evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'SkillForge Assessment', 'Team Validation'],
      icon: 'Atom',
    },
    {
      id: 'skill-python',
      name: 'Python',
      slug: 'python',
      category: 'backend',
      status: 'VERIFIED',
      verificationLevel: 3,
      trustScore: 89,
      confidenceScore: 92,
      evidenceConfidence: 92,
      projectsFound: 6,
      repositoriesFound: 4,
      assessmentScore: 88,
      skillMaturity: 'Advanced',
      yearsOfExposure: 3.8,
      lastActiveDate: 'Sep 2026',
      verifiedAt: '2026-03-05',
      verificationHash: '0x3a19...90cf',
      level: 'Advanced',
      evidenceCounts: { projects: 6, repos: 4, certifications: 1 },
      evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'LinkedIn', 'Certifications'],
      icon: 'Terminal',
    },
    {
      id: 'skill-ml',
      name: 'Machine Learning',
      slug: 'machine-learning',
      category: 'ai',
      status: 'VERIFIED',
      verificationLevel: 4,
      trustScore: 92,
      confidenceScore: 90,
      evidenceConfidence: 90,
      projectsFound: 4,
      repositoriesFound: 3,
      semanticMatchScore: 84,
      assessmentScore: 90,
      skillMaturity: 'Proficient',
      yearsOfExposure: 2.2,
      lastActiveDate: 'Jul 2026',
      level: 'Intermediate',
      evidenceCounts: { projects: 4, repos: 3, certifications: 1 },
      evidenceSources: ['Resume', 'GitHub', 'Coursework', 'Documentation', 'Assessment'],
      icon: 'Brain',
    },
    {
      id: 'skill-git',
      name: 'Git',
      slug: 'git',
      category: 'devops',
      status: 'VERIFIED',
      verificationLevel: 2,
      trustScore: 62,
      confidenceScore: 75,
      evidenceConfidence: 75,
      projectsFound: 2,
      repositoriesFound: 3,
      skillMaturity: 'Competent',
      yearsOfExposure: 3.0,
      lastActiveDate: 'Sep 2026',
      verifiedAt: '2026-02-28',
      verificationHash: '0x992b...fa14',
      level: 'Intermediate',
      evidenceCounts: { projects: 2, repos: 3, certifications: 1 },
      evidenceSources: ['Resume', 'GitHub Profile', 'LinkedIn'],
      icon: 'GitBranch',
    },
    {
      id: 'skill-nodejs',
      name: 'Node.js',
      slug: 'nodejs',
      category: 'backend',
      status: 'CLAIMED',
      verificationLevel: 1,
      trustScore: 30,
      confidenceScore: 38,
      evidenceConfidence: 38,
      projectsFound: 1,
      repositoriesFound: 0,
      skillMaturity: 'Competent',
      yearsOfExposure: 1.5,
      lastActiveDate: 'Jan 2026',
      level: 'Intermediate',
      evidenceCounts: { projects: 1, repos: 0, certifications: 0 },
      evidenceSources: ['Profile Bio', 'Resume'],
      icon: 'Server',
    },
    {
      id: 'skill-ruby',
      name: 'Ruby',
      slug: 'ruby',
      category: 'backend',
      status: 'VERIFIED',
      verificationLevel: 3,
      trustScore: 86,
      confidenceScore: 88,
      evidenceConfidence: 88,
      projectsFound: 3,
      repositoriesFound: 2,
      isUnsupported: false,
      unsupportedReason: undefined,
      skillMaturity: 'Advanced',
      yearsOfExposure: 2.8,
      lastActiveDate: 'Sep 2026',
      level: 'Advanced',
      evidenceCounts: { projects: 3, repos: 2, certifications: 1 },
      evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'LinkedIn'],
      icon: 'Layers',
    },
  ],
  assessmentHistory: [
    {
      id: 'hist-react',
      skillName: 'React',
      slug: 'react',
      score: 92,
      status: 'Passed',
      date: 'Mar 9, 2026',
      confidenceScore: 92,
      certificateId: 'CERT-SF-92841',
      verificationHash: '0x7c49...32e1',
    },
    {
      id: 'hist-python',
      skillName: 'Python',
      slug: 'python',
      score: 88,
      status: 'Passed',
      date: 'Mar 5, 2026',
      confidenceScore: 88,
      certificateId: 'CERT-SF-88120',
      verificationHash: '0x3a19...90cf',
    },
    {
      id: 'hist-git',
      skillName: 'Git',
      slug: 'git',
      score: 81,
      status: 'Passed',
      date: 'Feb 28, 2026',
      confidenceScore: 81,
      certificateId: 'CERT-SF-81099',
      verificationHash: '0x992b...fa14',
    },
    {
      id: 'hist-ml',
      skillName: 'Machine Learning',
      slug: 'machine-learning',
      score: 0,
      status: 'Pending',
      date: 'In Queue',
    },
  ],
};

export const MOCK_CANDIDATES: Candidate[] = [
  INITIAL_CANDIDATE,
  {
    id: 'cand-sarah-chen',
    username: 'sarahchen',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'AI / ML Research Engineer',
    university: 'Stanford University',
    bio: 'Specializing in fine-tuning small LLMs, agentic loops, and multi-modal embeddings.',
    location: 'Palo Alto, CA',
    githubUrl: 'https://github.com/sarahchen-ai',
    portfolioUrl: 'https://sarahchen.io',
    email: 'sarah.chen@cs.stanford.edu',
    overallConfidence: 93,
    verifiedSkillsCount: 4,
    lookingForTeam: true,
    hackathon: 'HackGenesis 2026',
    passportId: 'SF-PASS-9102-S1',
    issuedAt: 'March 2026',
    signature: '0x44ab...1809 (ECDSA Verified)',
    skills: [
      {
        id: 's-pt',
        name: 'PyTorch',
        slug: 'pytorch',
        category: 'ai',
        status: 'VERIFIED',
        verificationLevel: 5,
        trustScore: 97,
        confidenceScore: 96,
        assessmentScore: 96,
        skillMaturity: 'Mastery',
        yearsOfExposure: 4.0,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 4, repos: 3, certifications: 2 },
        evidenceSources: ['Resume', 'GitHub', 'Assessment', 'Team Validation'],
        verifiedAt: '2026-03-10',
        verificationHash: '0x88bb...2100',
        icon: 'Brain',
      },
      {
        id: 's-py',
        name: 'Python',
        slug: 'python',
        category: 'backend',
        status: 'VERIFIED',
        verificationLevel: 4,
        trustScore: 94,
        confidenceScore: 94,
        assessmentScore: 94,
        skillMaturity: 'Advanced',
        yearsOfExposure: 3.5,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 3, repos: 2, certifications: 1 },
        evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'Assessment'],
        verifiedAt: '2026-03-08',
        verificationHash: '0x3310...8811',
        icon: 'Terminal',
      },
      {
        id: 's-lc',
        name: 'LangChain & RAG',
        slug: 'langchain',
        category: 'ai',
        status: 'VERIFIED',
        verificationLevel: 4,
        trustScore: 90,
        confidenceScore: 91,
        assessmentScore: 91,
        skillMaturity: 'Advanced',
        yearsOfExposure: 2.0,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 2, repos: 1, certifications: 1 },
        evidenceSources: ['Resume', 'GitHub', 'Assessment'],
        verifiedAt: '2026-03-02',
        verificationHash: '0x22df...1244',
        icon: 'Cpu',
      },
      {
        id: 's-fastapi',
        name: 'FastAPI',
        slug: 'fastapi',
        category: 'backend',
        status: 'VERIFIED',
        verificationLevel: 3,
        trustScore: 78,
        confidenceScore: 89,
        assessmentScore: 89,
        skillMaturity: 'Proficient',
        yearsOfExposure: 2.2,
        lastActiveDate: 'Feb 2026',
        evidenceCounts: { projects: 2, repos: 1, certifications: 0 },
        evidenceSources: ['Resume', 'GitHub Repositories'],
        verifiedAt: '2026-02-25',
        verificationHash: '0x19fa...8743',
        icon: 'Server',
      },
    ],
    assessmentHistory: [
      { id: 'h1', skillName: 'PyTorch', slug: 'pytorch', score: 96, status: 'Passed', date: 'Mar 10, 2026', confidenceScore: 96 },
      { id: 'h2', skillName: 'Python', slug: 'python', score: 94, status: 'Passed', date: 'Mar 8, 2026', confidenceScore: 94 },
    ],
  },
  {
    id: 'cand-marcus-vance',
    username: 'marcusvance',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Smart Contract & Rust Engineer',
    university: 'MIT',
    bio: 'Security-first smart contracts, EVM internals, and zero-knowledge circuit development.',
    location: 'Cambridge, MA',
    githubUrl: 'https://github.com/marcusvance-sec',
    portfolioUrl: 'https://mvance.eth.limo',
    email: 'mvance@mit.edu',
    overallConfidence: 89,
    verifiedSkillsCount: 3,
    lookingForTeam: true,
    hackathon: 'HackGenesis 2026',
    passportId: 'SF-PASS-7721-M4',
    issuedAt: 'February 2026',
    signature: '0x991c...de32 (ECDSA Verified)',
    skills: [
      {
        id: 's-sol',
        name: 'Solidity',
        slug: 'solidity',
        category: 'web3',
        status: 'VERIFIED',
        verificationLevel: 4,
        trustScore: 92,
        confidenceScore: 92,
        assessmentScore: 92,
        skillMaturity: 'Advanced',
        yearsOfExposure: 2.8,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 3, repos: 2, certifications: 1 },
        evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'Assessment'],
        verifiedAt: '2026-03-01',
        verificationHash: '0x4f12...ba99',
        icon: 'Layers',
      },
      {
        id: 's-rust',
        name: 'Rust',
        slug: 'rust',
        category: 'backend',
        status: 'VERIFIED',
        verificationLevel: 4,
        trustScore: 88,
        confidenceScore: 88,
        assessmentScore: 88,
        skillMaturity: 'Advanced',
        yearsOfExposure: 2.5,
        lastActiveDate: 'Feb 2026',
        evidenceCounts: { projects: 2, repos: 2, certifications: 0 },
        evidenceSources: ['Resume', 'GitHub', 'Assessment'],
        verifiedAt: '2026-02-20',
        verificationHash: '0xbb29...71fe',
        icon: 'Code',
      },
      {
        id: 's-ts',
        name: 'TypeScript',
        slug: 'typescript',
        category: 'frontend',
        status: 'VERIFIED',
        verificationLevel: 3,
        trustScore: 76,
        confidenceScore: 87,
        assessmentScore: 87,
        skillMaturity: 'Proficient',
        yearsOfExposure: 2.0,
        lastActiveDate: 'Feb 2026',
        evidenceCounts: { projects: 2, repos: 1, certifications: 0 },
        evidenceSources: ['Resume', 'GitHub Repositories'],
        verifiedAt: '2026-02-15',
        verificationHash: '0x10ef...8822',
        icon: 'FileCode',
      },
    ],
    assessmentHistory: [
      { id: 'h3', skillName: 'Solidity', slug: 'solidity', score: 92, status: 'Passed', date: 'Mar 1, 2026', confidenceScore: 92 },
      { id: 'h4', skillName: 'Rust', slug: 'rust', score: 88, status: 'Passed', date: 'Feb 20, 2026', confidenceScore: 88 },
    ],
  },
  {
    id: 'cand-priya-patel',
    username: 'priyapatel',
    name: 'Priya Patel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Frontend Architect & UX Designer',
    university: 'UC Berkeley',
    bio: 'Obsessed with fluid micro-interactions, responsive accessible UI, and Next.js 15.',
    location: 'Berkeley, CA',
    githubUrl: 'https://github.com/priyapatel-ui',
    portfolioUrl: 'https://priyapatel.design',
    email: 'priyapatel@berkeley.edu',
    overallConfidence: 94,
    verifiedSkillsCount: 3,
    lookingForTeam: false,
    hackathon: 'HackGenesis 2026',
    passportId: 'SF-PASS-5541-P9',
    issuedAt: 'March 2026',
    signature: '0x6e1b...9045 (ECDSA Verified)',
    skills: [
      {
        id: 's-next',
        name: 'Next.js',
        slug: 'nextjs',
        category: 'frontend',
        status: 'VERIFIED',
        verificationLevel: 5,
        trustScore: 96,
        confidenceScore: 95,
        assessmentScore: 95,
        skillMaturity: 'Mastery',
        yearsOfExposure: 3.5,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 4, repos: 3, certifications: 1 },
        evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'Assessment', 'Team Validation'],
        verifiedAt: '2026-03-08',
        verificationHash: '0x712a...ca09',
        icon: 'Globe',
      },
      {
        id: 's-tw',
        name: 'Tailwind CSS',
        slug: 'tailwindcss',
        category: 'frontend',
        status: 'VERIFIED',
        verificationLevel: 5,
        trustScore: 97,
        confidenceScore: 96,
        assessmentScore: 96,
        skillMaturity: 'Mastery',
        yearsOfExposure: 4.0,
        lastActiveDate: 'Mar 2026',
        evidenceCounts: { projects: 5, repos: 4, certifications: 1 },
        evidenceSources: ['Resume', 'GitHub', 'Portfolio', 'Assessment'],
        verifiedAt: '2026-03-06',
        verificationHash: '0x8891...3351',
        icon: 'Palette',
      },
      {
        id: 's-fig',
        name: 'Figma to Code',
        slug: 'figma',
        category: 'frontend',
        status: 'VERIFIED',
        verificationLevel: 4,
        trustScore: 89,
        confidenceScore: 91,
        assessmentScore: 91,
        skillMaturity: 'Advanced',
        yearsOfExposure: 3.0,
        lastActiveDate: 'Feb 2026',
        evidenceCounts: { projects: 3, repos: 1, certifications: 0 },
        evidenceSources: ['Resume', 'Portfolio', 'Assessment'],
        verifiedAt: '2026-02-28',
        verificationHash: '0x9928...cb22',
        icon: 'Layout',
      },
    ],
    assessmentHistory: [
      { id: 'h5', skillName: 'Next.js', slug: 'nextjs', score: 95, status: 'Passed', date: 'Mar 8, 2026', confidenceScore: 95 },
    ],
  },
  {
    id: 'cand-david-kim',
    username: 'davidkim',
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Cloud & Distributed Systems',
    university: 'University of Waterloo',
    bio: 'Kubernetes wizard, Go backend services, and high-throughput event streaming.',
    location: 'Toronto, Canada',
    githubUrl: 'https://github.com/davidkim-sys',
    portfolioUrl: 'https://davidkim.cloud',
    email: 'david.kim@uwaterloo.ca',
    overallConfidence: 86,
    verifiedSkillsCount: 3,
    lookingForTeam: true,
    hackathon: 'HackGenesis 2026',
    passportId: 'SF-PASS-3312-D2',
    issuedAt: 'March 2026',
    signature: '0xaa12...bb90 (ECDSA Verified)',
    skills: [
      {
        id: 's-go',
        name: 'Go',
        slug: 'go',
        category: 'backend',
        status: 'VERIFIED',
        confidenceScore: 90,
        assessmentScore: 90,
        verifiedAt: '2026-03-07',
        verificationHash: '0x12bb...87aa',
        icon: 'Terminal',
      },
      {
        id: 's-docker',
        name: 'Docker',
        slug: 'docker',
        category: 'devops',
        status: 'VERIFIED',
        confidenceScore: 88,
        assessmentScore: 88,
        verifiedAt: '2026-03-02',
        verificationHash: '0x3344...bb88',
        icon: 'Box',
      },
      {
        id: 's-k8s',
        name: 'Kubernetes',
        slug: 'kubernetes',
        category: 'devops',
        status: 'VERIFIED',
        confidenceScore: 81,
        assessmentScore: 81,
        verifiedAt: '2026-02-18',
        verificationHash: '0x9988...1122',
        icon: 'Cloud',
      },
    ],
    assessmentHistory: [
      { id: 'h6', skillName: 'Go', slug: 'go', score: 90, status: 'Passed', date: 'Mar 7, 2026', confidenceScore: 90 },
    ],
  },
];

export const MOCK_ASSESSMENTS: Record<string, Assessment> = {
  'machine-learning': {
    id: 'assess-ml',
    skillName: 'Machine Learning',
    slug: 'machine-learning',
    category: 'AI & Data',
    level: 'Intermediate',
    estimatedMinutes: 5,
    totalQuestions: 4,
    passThreshold: 75,
    description: 'Verify your understanding of ML model evaluation, overfitting mitigation, embeddings, and vector similarity.',
    whatIsTested: [
      'Precision, Recall, and F1 tradeoffs',
      'Overfitting detection & L1/L2 regularization',
      'Cosine similarity vs Euclidean distance in RAG',
      'Data leakage pitfalls during feature normalization',
    ],
    questions: [
      {
        id: 'q-ml-1',
        questionNumber: 1,
        title: 'Metric Evaluation for Imbalanced Data',
        type: 'multiple-choice',
        difficulty: 'Medium',
        scenario: 'You are training a fraud detection model where only 0.2% of transactions are fraudulent. The model predicts 0 (not fraudulent) for every transaction, achieving 99.8% raw accuracy.',
        options: [
          { id: 'a', label: 'A', text: 'The model is production ready because 99.8% accuracy exceeds industry standards.' },
          { id: 'b', label: 'B', text: 'Accuracy is misleading here. You should evaluate using PR-AUC (Precision-Recall) and F1 or Recall at target precision.', explanation: 'In severe class imbalance, accuracy is dominated by the majority class.' },
          { id: 'c', label: 'C', text: 'You should switch to Mean Squared Error (MSE) to penalize small deviations.' },
          { id: 'd', label: 'D', text: 'Increase the batch size to 4096 so the minority class is naturally absorbed.' },
        ],
        correctOptionId: 'b',
        hint: 'Consider how the vast majority class skews naive accuracy metrics.',
      },
      {
        id: 'q-ml-2',
        questionNumber: 2,
        title: 'Spot the Data Leakage Bug',
        type: 'code-debugging',
        difficulty: 'Hard',
        scenario: 'Analyze the preprocessing pipeline snippet below. What critical issue occurs that leads to optimistic validation scores?',
        language: 'python',
        codeSnippet: `from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Features X, target y
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X) # <-- Leak occurs here!

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)`,
        options: [
          { id: 'a', label: 'A', text: 'StandardScaler should only be used on categorical variables.' },
          { id: 'b', label: 'B', text: 'Data leakage: The scaler is fitted on the entire dataset before splitting, leaking test distribution mean and variance into training.', explanation: 'Fit the scaler strictly on X_train, then transform X_test.' },
          { id: 'c', label: 'C', text: 'random_state=42 introduces pseudo-random bias to the gradient descent optimizer.' },
          { id: 'd', label: 'D', text: 'test_size=0.2 must be an integer rather than a float.' },
        ],
        correctOptionId: 'b',
        hint: 'When should statistics (mean, variance) be calculated relative to the test set?',
      },
      {
        id: 'q-ml-3',
        questionNumber: 3,
        title: 'Vector Search Metric Selection',
        type: 'architecture',
        difficulty: 'Medium',
        scenario: 'In a Retrieval-Augmented Generation (RAG) system using OpenAI text-embedding-3-small vectors (which are normalized to unit length L2=1), how do Cosine Similarity and Dot Product compare?',
        options: [
          { id: 'a', label: 'A', text: 'Cosine similarity and Dot Product produce mathematically identical ranking for unit-normalized vectors.', explanation: 'Cosine(u, v) = (u . v) / (||u|| * ||v||). When ||u|| = ||v|| = 1, Cosine = Dot Product.' },
          { id: 'b', label: 'B', text: 'Dot product fails because negative vectors invert search results.' },
          { id: 'c', label: 'C', text: 'Cosine similarity is O(N^2) while dot product is O(log N).' },
          { id: 'd', label: 'D', text: 'You must use Manhattan (L1) distance for embeddings with dimension > 512.' },
        ],
        correctOptionId: 'a',
      },
      {
        id: 'q-ml-4',
        questionNumber: 4,
        title: 'Combating Overfitting in Deep Neural Networks',
        type: 'multiple-choice',
        difficulty: 'Medium',
        scenario: 'During training, your validation loss begins rising after epoch 12 while training loss continues decreasing toward zero. Which intervention is best practice?',
        options: [
          { id: 'a', label: 'A', text: 'Double the learning rate and remove dropout layers.' },
          { id: 'b', label: 'B', text: 'Apply early stopping at epoch 12, introduce dropout or weight decay (L2), and gather/augment training samples.', explanation: 'Rising validation loss with declining training loss is classic overfitting.' },
          { id: 'c', label: 'C', text: 'Continue training for 100 more epochs until validation loss stabilizes.' },
          { id: 'd', label: 'D', text: 'Disable batch normalization layers so weights can freely grow.' },
        ],
        correctOptionId: 'b',
      },
    ],
  },
  'nodejs': {
    id: 'assess-nodejs',
    skillName: 'Node.js',
    slug: 'nodejs',
    category: 'Backend',
    level: 'Intermediate',
    estimatedMinutes: 5,
    totalQuestions: 3,
    passThreshold: 75,
    description: 'Verify your proficiency in the Node.js event loop, asynchronous concurrency, streams, and error handling.',
    whatIsTested: [
      'Event loop phases (microtasks vs macrotasks)',
      'Backpressure management in streams',
      'Uncaught exception & unhandled rejection resilience',
    ],
    questions: [
      {
        id: 'q-node-1',
        questionNumber: 1,
        title: 'Event Loop Execution Order',
        type: 'code-debugging',
        difficulty: 'Medium',
        scenario: 'What is the exact console output order of the following snippet?',
        language: 'javascript',
        codeSnippet: `console.log('1');
setTimeout(() => console.log('2'), 0);
Promise.resolve().then(() => console.log('3'));
process.nextTick(() => console.log('4'));
console.log('5');`,
        options: [
          { id: 'a', label: 'A', text: '1, 5, 2, 3, 4' },
          { id: 'b', label: 'B', text: '1, 5, 4, 3, 2', explanation: 'Synchronous (1, 5) -> process.nextTick microtask (4) -> Promise microtask (3) -> Timer macrotask (2).' },
          { id: 'c', label: 'C', text: '1, 3, 4, 5, 2' },
          { id: 'd', label: 'D', text: '1, 5, 3, 4, 2' },
        ],
        correctOptionId: 'b',
      },
      {
        id: 'q-node-2',
        questionNumber: 2,
        title: 'Handling Memory Backpressure in Large File Transfers',
        type: 'architecture',
        difficulty: 'Medium',
        scenario: 'An API endpoint reads a 4GB file from disk and sends it over an HTTP response. Using fs.readFile consumes 4GB of RAM and crashes the container. What is the production pattern?',
        options: [
          { id: 'a', label: 'A', text: 'Increase node --max-old-space-size to 8192.' },
          { id: 'b', label: 'B', text: 'Use fs.createReadStream() and pipe it to res (or stream.pipeline) with automatic backpressure handling.', explanation: 'Streams chunk data into small buffers (e.g. 64KB), keeping memory footprint tiny.' },
          { id: 'c', label: 'C', text: 'Convert the file to base64 and send it in a JSON body.' },
          { id: 'd', label: 'D', text: 'Read the file synchronously with fs.readFileSync inside a Promise.' },
        ],
        correctOptionId: 'b',
      },
      {
        id: 'q-node-3',
        questionNumber: 3,
        title: 'Cluster Mode and Worker Threads',
        type: 'multiple-choice',
        difficulty: 'Medium',
        scenario: 'When should a Node.js engineer use Worker Threads instead of the Cluster module?',
        options: [
          { id: 'a', label: 'A', text: 'When handling standard I/O bound HTTP REST requests.' },
          { id: 'b', label: 'B', text: 'When executing CPU-intensive tasks (e.g. image transformations, cryptographic hashing) requiring shared ArrayBuffers without spawning separate OS processes.', explanation: 'Worker threads allow sharing memory via SharedArrayBuffer for heavy CPU operations.' },
          { id: 'c', label: 'C', text: 'Worker threads are deprecated in Node.js 20+.' },
          { id: 'd', label: 'D', text: 'Only when connecting to SQLite databases.' },
        ],
        correctOptionId: 'b',
      },
    ],
  },
  'react': {
    id: 'assess-react',
    skillName: 'React',
    slug: 'react',
    category: 'Frontend',
    level: 'Advanced',
    estimatedMinutes: 5,
    totalQuestions: 5,
    passThreshold: 70,
    description: 'A short practical assessment designed to verify your understanding without unnecessary pressure.',
    whatIsTested: [
      'Stale closures in hooks and callbacks',
      'State immutability and reconciliation triggers',
      'useTransition for responsive input rendering',
      'React Server Components composition boundaries',
      'useEffect cleanup lifecycle timing',
    ],
    questions: [
      {
        id: 'q-react-1',
        questionNumber: 1,
        title: 'Understanding Stale Closures in Hooks',
        type: 'code-debugging',
        difficulty: 'Medium',
        scenario: 'In a timer component, a counter increment fails to advance past 1: useEffect(() => { const t = setInterval(() => setCount(count + 1), 1000); return () => clearInterval(t); }, []); What causes this bug?',
        language: 'tsx',
        codeSnippet: `const [count, setCount] = useState(0);

useEffect(() => {
  const timer = setInterval(() => {
    setCount(count + 1); // <-- Stale closure
  }, 1000);
  return () => clearInterval(timer);
}, []);`,
        options: [
          { id: 'a', label: 'A', text: 'setInterval cannot be called inside useEffect in React 18+.' },
          { id: 'b', label: 'B', text: 'The effect captures the initial count (0) in its closure; setCount(count + 1) repeatedly evaluates 0 + 1 = 1. Use setCount(prev => prev + 1) instead.', explanation: 'Functional updater receives latest state without closure capture.' },
          { id: 'c', label: 'C', text: 'clearInterval must be executed synchronously before setInterval.' },
          { id: 'd', label: 'D', text: 'React state updates are asynchronous and cannot be triggered from timer intervals.' },
        ],
        correctOptionId: 'b',
        hint: 'Consider what value of count is captured inside the effect callback on mount.',
      },
      {
        id: 'q-react-2',
        questionNumber: 2,
        title: 'State Immutability and Reconciliation',
        type: 'code-debugging',
        difficulty: 'Medium',
        scenario: 'A developer mutates an existing array with items.push(newItem) and calls setItems(items), but the UI fails to re-render. Why does React ignore this update?',
        language: 'tsx',
        codeSnippet: `const [items, setItems] = useState(['Alpha', 'Beta']);

function handleAdd(newItem: string) {
  items.push(newItem);
  setItems(items); // Component does not re-render!
}`,
        options: [
          { id: 'a', label: 'A', text: 'React checks state equality using Object.is(). Mutating the existing array produces identical references, causing React to bail out of rendering. Use setItems([...items, newItem]).', explanation: 'React requires a new object reference to detect change.' },
          { id: 'b', label: 'B', text: 'React requires items.concat() rather than items.push() for internal garbage collection.' },
          { id: 'c', label: 'C', text: 'Arrays cannot be stored directly in useState without wrapping in useRef.' },
          { id: 'd', label: 'D', text: 'The setter function setItems only accepts primitive values like strings and numbers.' },
        ],
        correctOptionId: 'a',
        hint: 'How does React determine if state has actually changed during reconciliation?',
      },
      {
        id: 'q-react-3',
        questionNumber: 3,
        title: 'useTransition for Responsive Search Inputs',
        type: 'multiple-choice',
        difficulty: 'Medium',
        scenario: 'You have a large list of 5,000 hackathon candidates. Typing in the search input feels sluggish because filtering blocks the main thread. How does useTransition resolve this?',
        options: [
          { id: 'a', label: 'A', text: 'It offloads the entire React fiber tree computation to a Web Worker thread.' },
          { id: 'b', label: 'B', text: 'It marks the filter state update as a non-urgent transition, allowing urgent input keystrokes to interrupt and render immediately without UI freeze.', explanation: 'useTransition marks state updates as transitions that can be interrupted by urgent user interactions.' },
          { id: 'c', label: 'C', text: 'It replaces useState with local browser cache lookups in localStorage.' },
          { id: 'd', label: 'D', text: 'It automatically debounces keystrokes by 500ms before triggering state updates.' },
        ],
        correctOptionId: 'b',
        hint: 'Think about concurrent React and how urgent events differ from non-urgent transitions.',
      },
      {
        id: 'q-react-4',
        questionNumber: 4,
        title: 'React Server Components Composition',
        type: 'architecture',
        difficulty: 'Medium',
        scenario: 'In Next.js App Router, how can a Client Component contain a Server Component that fetches data directly without converting that Server Component into a client bundle?',
        options: [
          { id: 'a', label: 'A', text: 'Pass the Server Component as the children prop (or other JSX prop) to the Client Component wrapper.', explanation: 'Composition pattern: Server component passed as children prop maintains server execution.' },
          { id: 'b', label: 'B', text: 'Import the Server Component directly with dynamic import() inside useEffect.' },
          { id: 'c', label: 'C', text: 'Mark the Client Component with "use server-client" at the top.' },
          { id: 'd', label: 'D', text: 'It is impossible; any component imported by a Client Component must run on the client.' },
        ],
        correctOptionId: 'a',
        hint: 'How does JSX composition allow server-rendered slots inside client boundaries?',
      },
      {
        id: 'q-react-5',
        questionNumber: 5,
        title: 'useEffect Cleanup Lifecycle Timing',
        type: 'multiple-choice',
        difficulty: 'Medium',
        scenario: 'A component subscribes to a global event listener inside useEffect. When does React execute the returned cleanup function?',
        options: [
          { id: 'a', label: 'A', text: 'Only when the browser window or tab is closed.' },
          { id: 'b', label: 'B', text: 'Before the component unmounts, and before re-running the effect on subsequent renders when dependencies change.', explanation: 'React runs cleanup before applying next effect and upon unmount to prevent leaks.' },
          { id: 'c', label: 'C', text: 'Immediately after the JSX render phase completes before the DOM updates.' },
          { id: 'd', label: 'D', text: 'Every time any parent component renders, regardless of dependency array values.' },
        ],
        correctOptionId: 'b',
        hint: 'When does React clear subscriptions to prevent memory leaks between renders?',
      },
    ],
  },
};

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-codeforge',
    name: 'CodeForge',
    slug: 'codeforge',
    tagline: 'High-Performance Developer Tooling & Verification',
    description: 'Building transparent skill verification and high-speed hackathon developer tooling for SkillSprint 2026.',
    hackathon: 'SkillSprint 2026',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    lookingFor: ['Frontend Developer'],
    openSpots: 1,
    members: [
      {
        id: 'tm-sam',
        candidateId: 'cand-sam',
        name: 'Sam',
        username: 'sam_backend',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        role: 'Backend',
        primarySkill: 'Go & Distributed Systems',
        confidence: 94,
        isLead: false,
      },
      {
        id: 'tm-maya',
        candidateId: 'cand-maya',
        name: 'Maya',
        username: 'maya_ux',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        role: 'UI/UX',
        primarySkill: 'Design Systems & Figma',
        confidence: 91,
        isLead: false,
      },
      {
        id: 'tm-you',
        candidateId: 'cand-you',
        name: 'You',
        username: 'you_aiml',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        role: 'AI/ML',
        primarySkill: 'LLMs & Agentic Systems',
        confidence: 95,
        isLead: true,
      },
    ],
    skillCoverage: [
      { category: 'AI & Machine Learning', percentage: 95, skills: ['PyTorch', 'Agentic Systems', 'Python'] },
      { category: 'Backend & APIs', percentage: 92, skills: ['Go', 'PostgreSQL', 'Docker'] },
      { category: 'UI/UX & Design', percentage: 90, skills: ['Design Systems', 'Figma', 'Prototyping'] },
      { category: 'Frontend (Open Role)', percentage: 25, skills: ['Basic HTML/CSS'] },
    ],
  },
  {
    id: 'team-nexus-ai',
    name: 'Nexus AI',
    slug: 'nexus-ai',
    tagline: 'Autonomous Clinical Trial Workflow Agents',
    description: 'We are developing autonomous multi-agent systems that extract and cross-verify pharmaceutical clinical trial criteria from FDA filings in real-time.',
    hackathon: 'SkillSprint 2026',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    lookingFor: ['AI/ML Engineer', 'Full Stack Developer', 'DevOps'],
    openSpots: 1,
    members: [
      {
        id: 'tm-1',
        candidateId: 'cand-sarah-chen',
        name: 'Sarah Chen',
        username: 'sarahchen',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        role: 'AI / ML Lead',
        primarySkill: 'PyTorch (96%)',
        confidence: 96,
        isLead: true,
      },
      {
        id: 'tm-2',
        candidateId: 'cand-david-kim',
        name: 'David Kim',
        username: 'davidkim',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        role: 'Cloud & Infrastructure',
        primarySkill: 'Go (90%)',
        confidence: 90,
        isLead: false,
      },
    ],
    skillCoverage: [
      { category: 'AI & Machine Learning', percentage: 95, skills: ['PyTorch', 'LangChain', 'Python'] },
      { category: 'Cloud & DevOps', percentage: 88, skills: ['Go', 'Docker', 'Kubernetes'] },
      { category: 'Frontend & UI', percentage: 40, skills: ['Basic HTML/CSS'] },
      { category: 'Smart Contracts', percentage: 0, skills: [] },
    ],
  },
  {
    id: 'team-zeroproof',
    name: 'ZeroProof',
    slug: 'zeroproof',
    tagline: 'Decentralized Student Builder Credentials',
    description: 'Building zero-knowledge verifiable proof-of-competence credentials that allow developers to prove hackathon skills without doxxing identity.',
    hackathon: 'HackGenesis 2026',
    avatar: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=150&auto=format&fit=crop&q=80',
    lookingFor: ['Frontend Engineer', 'UI/UX Specialist'],
    openSpots: 2,
    members: [
      {
        id: 'tm-3',
        candidateId: 'cand-marcus-vance',
        name: 'Marcus Vance',
        username: 'marcusvance',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        role: 'Smart Contract Lead',
        primarySkill: 'Solidity (92%)',
        confidence: 92,
        isLead: true,
      },
    ],
    skillCoverage: [
      { category: 'Smart Contracts', percentage: 92, skills: ['Solidity', 'Rust', 'EVM'] },
      { category: 'Backend', percentage: 85, skills: ['TypeScript', 'Rust'] },
      { category: 'Frontend & UI', percentage: 35, skills: ['Basic React'] },
      { category: 'AI & ML', percentage: 10, skills: [] },
    ],
  },
  {
    id: 'team-echohealth',
    name: 'EchoHealth',
    slug: 'echohealth',
    tagline: 'Real-Time Edge Biometric Audio Diagnostics',
    description: 'Analyzing micro-cough and vocal acoustic frequencies on-device to predict respiratory strain before symptoms manifest.',
    hackathon: 'HackGenesis 2026',
    avatar: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=150&auto=format&fit=crop&q=80',
    lookingFor: ['Full Stack Dev', 'Mobile Engineer'],
    openSpots: 2,
    members: [
      {
        id: 'tm-4',
        candidateId: 'cand-priya-patel',
        name: 'Priya Patel',
        username: 'priyapatel',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        role: 'Frontend & Product Designer',
        primarySkill: 'Next.js (95%)',
        confidence: 95,
        isLead: true,
      },
    ],
    skillCoverage: [
      { category: 'Frontend & UI', percentage: 96, skills: ['Next.js', 'Tailwind CSS', 'Figma'] },
      { category: 'AI & Audio', percentage: 70, skills: ['Python Audio DSP'] },
      { category: 'Backend & Cloud', percentage: 45, skills: ['Node.js'] },
      { category: 'Smart Contracts', percentage: 0, skills: [] },
    ],
  },
];

export const INITIAL_INVITES: TeamInvite[] = [
  {
    id: 'inv-1',
    teamId: 'team-nexus-ai',
    teamName: 'Nexus AI',
    teamAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    invitedCandidateUsername: 'alexmorgan',
    role: 'Lead Full Stack Engineer',
    hackathon: 'HackGenesis 2026',
    status: 'pending',
    sentAt: '2 hours ago',
    message: 'Hey Alex! Loved seeing your Verified React (92%) and Python (88%) badges. We need someone to connect our PyTorch inference pipeline to a slick interactive Next.js dashboard.',
  },
  {
    id: 'inv-2',
    teamId: 'team-zeroproof',
    teamName: 'ZeroProof',
    teamAvatar: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=150&auto=format&fit=crop&q=80',
    invitedCandidateUsername: 'alexmorgan',
    role: 'Frontend & Integration Engineer',
    hackathon: 'HackGenesis 2026',
    status: 'pending',
    sentAt: 'Yesterday',
    message: 'Hi Alex, we are looking for a verified frontend developer to build the credential claim UI for ZeroProof. Let us know if you want to join!',
  },
];
